title = "Arberia Theme"
baseURL = "https://example.com/"
relativeURLs = "True"
languageName = "En"
languageCode = "en-us"
theme = "arberia"


# To list the most relevant pages on the front page or similar, 
# you should use the site.Params.mainSections list instead of comparing 
# section names to hard-coded values like "posts" or "post".
# [params]
#   mainSections = ['posts',]


# [outputs]
#  home = ["HTML", "AMP", "RSS", "JSON"]

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]

[markup.goldmark.renderer] # Controllare cosa faccia
  unsafe = true

[permalinks]
  posts = "/:title/"

[minify]
  minifyOutput = true



############################# Plugins ##############################
# CSS Plugins
# [[params.plugins.css]]
# link = "css/Custom.css"
# [[params.plugins.css]]
# link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"

# JS Plugins
# [[params.plugins.js]]
# link = "js/customJS.js"


# Generate favicon with https://realfavicongenerator.net/
# and copy favicon folder (name it facicon) to static/ folder
[assets]
  favicon = "favicon/favicon.ico"
  favicon16x16 = "favicon/favicon-16x16.png>"
  favicon32x32 = "favicon/favicon-32x32.png"
  apple_touch_icon = "favicon/apple-touch-icon.png"
  safari_pinned_tab = "favicon/safari-pinned-tab.svg"
  # safari_color = "18354c"
  # theme_color = "#18354c"
  # msapplication_TileColor = "#ffc40d"



[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false
    tocMinWordCount = 100 # Minimum word count to display the Table of Contents

# [tableOfContents]
#   startLevel = 2
#   endLevel = 5
#   ordered = false
#   tocMinWordCount = 500



######################################
#  Menu
# [[menu.main]]
# identifier = "home"
# pre = ""
# post = ""
# name = "Home"
# url = "/"
# title = ""
# weight = 1

[[menu.main]]
identifier = "portfolio"
pre = "fa fa-drafting-compass"
post = ""
name = "Portfolio"
url = "/portfolio"
title = ""
weight = 2


[[menu.main]]
identifier = "tutorial"
pre = "fa fa-graduation-cap"
post = ""
name = "Tutorial"
url = "#"
title = ""
weight = 3

[[menu.main]]
identifier = "python_tutorials"
pre = "fa fa-graduation-cap"
post = "In deep articles and tutorials"
name = "Python Tutorials"
url = "/python-tutorials/"
title = ""
weight = 4
parent = "tutorial"
[menu.main.params]
  color = "#ff7e73"

[[menu.main]]
identifier = "python_topics"
pre = "fa fa-tag"
post = "Focus on specific area level"
name = "Python Topics →"
url = "/python-topics/"
title = ""
weight = 5
parent = "tutorial"
[menu.main.params]
  color = "#abe5b1"

[[menu.main]]
identifier = "video"
pre = "fa fa-film"
post = "Step-by-step video lesson"
name = "Video Tutorial"
url = "/portfolio/"
title = ""
weight = 6
parent = "tutorial"
[menu.main.params]
  color = "#abe0e5"

[[menu.main]]
identifier = "quizzies"
pre = "fa fa-trophy"
post = "Check your learning progress"
name = "Quizzies→"
url = "/quizzies/"
title = ""
weight = 7
parent = "tutorial"
[menu.main.params]
  color = "#ffc873"

[[menu.main]]
identifier = "unlock"
pre = "fa fa-star text-warning"
post = ""
name = "Unlock All Content"
url = "/quizzies/"
title = ""
weight = 8
parent = "tutorial"
[menu.main.params]
  color = ""
  bordertop = true

[[menu.main]]
identifier = "libri"
pre = ""
post = ""
name = "Libri"
url = "/libri"
title = ""
weight = 9

[[menu.main]]
identifier = "contact"
pre = ""
post = ""
name = "Contatti"
url = "/contatti/"
title = ""
weight = 10

[[menu.main]]
identifier = "about"
pre = ""
post = ""
name = "About "
url = "/about/"
title = ""
weight = 11


# [[menu.main]]
# identifier = "more"
# pre = ""
# post = ""
# name = "More"
# url = "/more/"
# title = ""
# weight = 10

# [[menu.main]]
# identifier = "python_newsletter"
# pre = ""
# post = ""
# name = "Python Newsletter"
# url = "/more/"
# title = ""
# weight = 11
# parent = "more"

# [[menu.main]]
# identifier = "python_podcast"
# pre = ""
# post = ""
# name = "Python Podcast"
# url = "/more/"
# title = ""
# weight = 11
# parent = "more"

# [[menu.main]]
# identifier = "python_job_board"
# pre = ""
# post = ""
# name = "Python Job Board →"
# url = "/more/"
# title = ""
# weight = 12
# parent = "more"


# Elenco colori da usare nel  menu 
			# "color: #ff7e73;
			# "color: #abe5b1;
			# "color: #abe0e5;
			# "color: #ffc873;
			# "color: #e5c6ab;
			# "color: #b8abe5; 

# Footer config
[footer]
enable = true
title = "||||"
greatings = "❤️ Happy Pythoning!"
  
[[menu.footer]]
  name = "Newsletter"
  link = "newsletter/"
  weight = 1

[[menu.footer]]
  name = "Podcast"
  link = "podcast/"
  weight = 2

[[menu.footer]]
  name = "Youtube"
  link = "youtube/"
  weight = 3

[[menu.footer]]
  name = "Twitter"
  link = "twitter/"
  weight = 4

[[menu.footer]]
  name = "Facebook"
  link = "facebook/"
  weight = 5

[[menu.footer]]
  name = "Instagram"
  link = "Instagram/"
  weight = 6

[[menu.footer]]
  name = "Python Tutorials"
  link = "python-tutorials/"
  weight = 7

[[menu.footer]]
  name = "Search"
  link = "search/"
  weight = 8

[[menu.footer]]
  name = "Privacy Policy"
  link = "privacy-policy/"
  weight = 9

[[menu.footer]]
  name = "Energy Policy"
  link = "energy-policy/"
  weight = 10

[[menu.footer]]
  name = "Contact"
  link = "contact/"
  weight = 11


############################# social site ########################
[[params.social]]
title = "medium"
icon = "fab fa-medium-m" # fontawesome icon : https://fontawesome.com/
link = "https://medium.com/@antedoro"

[[params.social]]
title = "facebook"
icon = "fab fa-facebook-f" # fontawesome icon : https://fontawesome.com/
link = "https://www.facebook.com/antedoroguitars"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon : https://fontawesome.com/
link = "https://twitter.com/AntedoroGuitars"

[[params.social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon : https://fontawesome.com/
link = "https://www.instagram.com/antedoroguitars/"

[[params.social]]
title = "pinterest"
icon = "fab fa-pinterest-p" # fontawesome icon : https://fontawesome.com/
link = "https://www.pinterest.it/antedoroguitars"

[[params.social]]
title = "telegram"
icon = "fab fa-telegram-plane" # fontawesome icon : https://fontawesome.com/
link = "https://telegram.me/antedoroguitars"