#################### default params ################################

# Brand Bar (inside header)
siteBrand = true
BrandLogo = "img/real-python-logo.svg"
# logo = "img/kodra-logo.jpg"
siteBrandWidth = 165
siteBrandHeight = 40
siteBrandFill = "#fff"
# Unit: em
siteBrandFontSize = 1
siteBrandFont = "Arial"
siteBrandFontColor = "white"

tagline = "New way of sound!"
description = "Learn Python online: Python tutorials for developers of all skill levels, Python books and courses, Python news, code examples, articles, and more."
keywords = "python, tutorials, video"
author = "Vincenzo Antedoro"
author_resume = "<strong>Vincenzo Antedoro</strong> è un ingegnere che aiuta chi vuole investire nelle rinnovabili. Per il resto si diverte insegnando col metodo del <em>learning by doing</em>."
YTChannelID = "UClA8GwWzurVCprEY6OsCvhw"
contact_form_action = "https://formspree.io/f/mvovbvga"

# #################### default parameters ################################
# post pagination
paginate = "5"
# post excerpt
summaryLength = "225"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-74607909-1" # example : UA-123-45
# unsafe html


disableSearch = false # default is false