#################### default params ################################

# Brand Bar (inside header)
siteBrand = true
# BrandLogo = "img/real-python-logo.svg"
# BrandLogo = ""
logo = "img/kodra-logo.jpg"
siteBrandWidth = 165
siteBrandHeight = 40
siteBrandFill = "#fff"
# Unit: em
siteBrandFontSize = 1
siteBrandFont = "Arial"
siteBrandFontColor = "white"

tagline = "New way of sound!"
description = "Learn Python online: Python tutorials for developers of all skill levels, Python books and courses, Python news, code examples, articles, and more."
keywords = "Insert keywords"
author = "Vincenzo Antedoro"
author_resume = "<strong>Vincenzo Antedoro</strong> è un ingegnere che aiuta chi vuole investire nelle rinnovabili. Per il resto si diverte insegnando col metodo del <em>learning by doing</em>."
YTChannelID = "UClA8GwWzurVCprEY6OsCvhw"
contact_form_action = "https://formspree.io/f/mvovbvga"

# #################### default parameters ################################
# numbero of post on pagination list
paginate = "6"
# summary lenght on list post 
summaryLength = "225"
# default is false
disableSearch = false 
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-74607909-1" # example : UA-123-45
# unsafe html


[share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = false
    Whatsapp = false
    Pinterest = false
    Tumblr = false
    HackerNews = true
    Reddit = false
    VK = false
    Buffer = false
    Xing = false
    Line = true
    Instapaper = false
    Pocket = false
    Flipboard = false
    Weibo = true
    Blogger = false
    Baidu = false
    Odnoklassniki = false
    Evernote = false
    Skype = false
    Trello = false
    Mix = false