baseURL = "https://realpython.com/"
languageName = "En"
languageCode = "en-us"
theme = "arberia"

title = "Real Python"
relativeURLs = "True"


#################### default parameters ################################
[params]
logo = "img/real-python-logo.svg"
logo_width = "200px"
tagline = "New way of sound!"
description = "Learn Python online: Python tutorials for developers of all skill levels, Python books and courses, Python news, code examples, articles, and more."
keywords = "python, tutorials, video"
author = "Vincenzo Antedoro"
author_resume = "Vincenzo Antedoro è un ingegnere che aiuta chi vuole investire nelle rinnovabili. Per il resto si diverte insegnando col metodo del learning by doing."
contact_form_action = "https://formspree.io/f/mvovbvga"

# post pagination
paginate = "3"
# post excerpt
summaryLength = "20"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-74607909-1" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer] # Controllare cosa faccia
unsafe = true

[permalinks]
  posts = "/:title/"

[minify]
  minifyOutput = false

############################# Plugins ##############################
# CSS Plugins
# [[params.plugins.css]]
# link = "css/realpython.css"
# [[params.plugins.css]]
# link = "css/font.css"
# [[params.plugins.css]]
# link = "css/glightbox.css"
# [[params.plugins.css]]
# link = "css/all.css"
# [[params.plugins.css]]
# link = "gfonts/font.08e909e5f3d4.css"
# [[params.plugins.css]]
# link = "gfonts/glightbox.min.f69035b3cab2.css"
# [[params.plugins.css]]
# link = "css/style.css"
# [[params.plugins.css]]
# link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"

# JS Plugins
# [[params.plugins.js]]
# link = "js/jquery.js"
# [[params.plugins.js]]
# link = "js/bootstrap.js"
# [[params.plugins.js]]
# link = "js/main.js"
# [[params.plugins.js]]
# link = "js/vendor.js"
# [[params.plugins.js]]
# link = "js/analytics.js"
# [[params.plugins.js]]
# link = "js/invisible.js"
# [[params.plugins.js]]
# link = "js/tag.js"
# [[params.plugins.js]]
# link = "js/popper.js"

[assets]
favicon = "favicon/favicon.ico"
favicon16x16 = "favicon/favicon-16x16.png>"
favicon32x32 = "favicon/favicon-32x32.png"
apple_touch_icon = "favicon/apple-touch-icon.png"
safari_pinned_tab = "favicon/safari-pinned-tab.svg>"



# [markup]
#   [markup.tableOfContents]
#     startLevel = 2
#     endLevel = 5
#     ordered = false
#     tocMinWordCount = 100 # Minimum word count to display the Table of Contents

[tableOfContents]
  startLevel = 2
  endLevel = 5
  ordered = false
  tocMinWordCount = 500

youtubeID = "UClA8GwWzurVCprEY6OsCvhw"

#  Menu
[[menu.main]]
identifier = "start-here"
pre = ""
post = ""
name = "Start Here"
url = "/start-here/"
title = ""
description = "In deep menu 1"
weight = 1

[[menu.main]]
identifier = "learn_python"
pre = "fa-trophy"
post = "fa-trophy"
name = "Learn Python"
url = "#"
title = ""
weight = 2

[[menu.main]]
identifier = "python_tutorials"
pre = "fa-trophy"
post = ""
name = "Python Tutorials"
url = "/python-tutorials/"
title = ""
description = "In deep menu 3"
weight = 3
parent = "learn_python"



[[menu.main]]
identifier = "python_topics"
pre = ""
post = "Focus on specific area level"
name = "Python Topics →"
url = "/python-topics/"
title = ""
description = "In deep menu 4"
weight = 4
parent = "learn_python"

[[menu.main]]
identifier = "quizzies"
pre = "Ciao"
post = "Vincenzo"
name = "Quizzies→"
url = "/quizzies/"
title = ""
description = "In deep menu 5"
weight = 5
parent = "learn_python"


[[menu.main]]
identifier = "more"
pre = "fa fa-fw mr-1 fa-film"
post = ""
name = "More"
url = "/more/"
title = ""
weight = 6

[[menu.main]]
identifier = "Python Newsletter"
pre = ""
post = ""
name = "Python Newsletter 1"
url = "/more/"
title = ""
weight = 7
parent = "more"

[[menu.main]]
identifier = "Python Podcast"
pre = ""
post = "post 9"
name = "Python Podcast 1 →"
url = "/more/"
title = ""
weight = 8
parent = "more"

[[menu.main]]
identifier = "Python Job Board"
pre = ""
post = ""
name = "Python Job Board1"
url = "/more/"
title = ""
weight = 9
parent = "more"

# Footer config
[footer]
enable = true
title = "||||"
greatings = "❤️ Happy Pythoning!"
  
[[menu.footer]]
  name = "Newsletter"
  link = "newsletter/"
  weight = 1

[[menu.footer]]
  name = "Podcast"
  link = "podcast/"
  weight = 2

[[menu.footer]]
  name = "Youtube"
  link = "youtube/"
  weight = 3

[[menu.footer]]
  name = "Twitter"
  link = "twitter/"
  weight = 4

[[menu.footer]]
  name = "Facebook"
  link = "facebook/"
  weight = 5

[[menu.footer]]
  name = "Instagram"
  link = "Instagram/"
  weight = 6

[[menu.footer]]
  name = "Python Tutorials"
  link = "python-tutorials/"
  weight = 7

[[menu.footer]]
  name = "Search"
  link = "search/"
  weight = 8

[[menu.footer]]
  name = "Privacy Policy"
  link = "privacy-policy/"
  weight = 9

[[menu.footer]]
  name = "Energy Policy"
  link = "energy-policy/"
  weight = 10

[[menu.footer]]
  name = "Contact"
  link = "contact/"
  weight = 11


############################# social site ########################
[[params.social]]
title = "medium"
icon = "fab fa-medium-m" # fontawesome icon : https://fontawesome.com/
link = "https://medium.com/@antedoro"

[[params.social]]
title = "facebook"
icon = "fab fa-facebook-f" # fontawesome icon : https://fontawesome.com/
link = "https://www.facebook.com/antedoroguitars"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon : https://fontawesome.com/
link = "https://twitter.com/AntedoroGuitars"

[[params.social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon : https://fontawesome.com/
link = "https://www.instagram.com/antedoroguitars/"

[[params.social]]
title = "pinterest"
icon = "fab fa-pinterest-p" # fontawesome icon : https://fontawesome.com/
link = "https://www.pinterest.it/antedoroguitars"

[[params.social]]
title = "telegram"
icon = "fab fa-telegram-plane" # fontawesome icon : https://fontawesome.com/
link = "https://telegram.me/antedoroguitars"