name = "Arberia Theme For Hugo"
license = "MIT"
licenselink = "https://github.com/antedoro/arberia/blob/main/LICENSE"
description = "Arberia Theme is a fully responsive theme for tech blogger with 4 single post layout and 2 list layout!"
homepage = "https://github.com/antedoro/arberia"
demosite = "https://arberiatheme.netlify.app/"
tags = ["blog", "clean", "responsive", "theme"]
features = ["post-with-sidebar", "video-post", "cover-post", "post-no-sidebar", "search", "disqus", "social-share", "SEO Optimized"]

[author]
  name = "antedoro"
  homepage = "https://github.com/antedoro"

[module]
  [module.hugoVersion]
 extended = true
 min = "0.148.1"
